env:
  browser: true
  commonjs: true
  es2021: true
  jquery: true
extends:
  - standard
parserOptions:
  ecmaVersion: 12
rules:
  arrow-parens:
    - warn
    - as-needed
globals:
  FullCalendar: readonly
  flatpickr: 'readonly'
